# Generated by Django 4.0.5 on 2023-07-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_marca_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Api',
            fields=[
                ('idProductoApi', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='media/productosApi')),
                ('precio', models.CharField(max_length=300, verbose_name='Precio')),
                ('precio_raw', models.CharField(max_length=300, verbose_name='Precio-Raw')),
                ('asset', models.CharField(max_length=300, verbose_name='Asset')),
                ('asset_raw', models.CharField(max_length=300, verbose_name='Asset-Raw')),
                ('estado', models.CharField(max_length=300, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'productoApi',
                'verbose_name_plural': 'productosApi',
                'ordering': ['idProductoApi'],
            },
        ),
    ]
