
openapi: 3.0.0
info:
  title: API
  description: esta api se encarga de manejar la informacion de la empresa DRAKON.CO. 
  version: 1.0.0


paths:
  /transporte:
    post:
      tags:
        - transporte
      summary: Realiza una solicitud POST para obtener datos de transporte
      responses:
        '200':
          description: Solicitud exitosa
        default:
          description: Ocurrió un error al enviar la solicitud POST

  /getbodega:
    get:
      tags:
        - bodega
      summary: Obtiene los productos de bodega
      responses:
        '200':
          description: Solicitud exitosa
        '500':
          description: Error interno del servidor

  /saludo:
    get:
      tags:
        - saludo
      summary: Obtiene el saludo desde la API
      responses:
        '200':
          description: Solicitud exitosa
        '500':
          description: Error interno del servidor

  /saldo:
    get:
      tags:
        - saldo
      summary: Obtiene el saldo desde la API
      responses:
        '200':
          description: Solicitud exitosa
        '500':
          description: Error interno del servidor

  /product_list:
    get:
      tags:
        - producto
      summary: Obtiene todos los productos
      responses:
        '200':
          description: Solicitud exitosa
      post:
        tags:
          - producto
        summary: Crea un nuevo producto
        responses:
          '201':
            description: Producto creado exitosamente
          '400':
            description: Solicitud incorrecta
      delete:
        tags:
          - producto
        summary: Elimina todos los productos
        responses:
          '204':
            description: No hay contenido

  /product_detail/{product_id}:
    get:
      tags:
        - producto
      summary: Obtiene un producto específico
      parameters:
        - in: path
          name: product_id
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Solicitud exitosa
        '404':
          description: Producto no encontrado
    put:
      tags:
        - producto
      summary: Actualiza un producto específico
      parameters:
        - in: path
          name: product_id
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Solicitud exitosa
        '202':
          description: Aceptado
        '400':
          description: Solicitud incorrecta
        '404':
          description: Producto no encontrado
    delete:
      tags:
        - producto
      summary: Elimina un producto específico
      parameters:
        - in: path
          name: product_id
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '204':
          description: No hay contenido

  /marcas_list:
    get:
      tags:
        - marca
      summary: Lista todas las marcas de los instrumentos
      responses:
        '200':
          description: Solicitud exitosa
        '400':
          description: Solicitud incorrecta
